[package]
name = "rest_api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = { version = "4.1.0" }
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.68"
kafka = "0.9"
